const styles = {
    container: { py: 8, mt: 5, bgcolor: "rgb(245,245,245)" },
    titleWrapper: { display: "flex", justifyContent: "center", mb: 3 },
    title: {
        border: "solid 2px rgba(54, 90, 202, 1)",
        borderRadius: 3,
        py: 1.5,
        px: 2.5,
        mt: 1,
        mb: 3,
        display: "inline-block",
        fontSize: "1.8rem",
        fontWeight: 700,
        textAlign: "center",
        color: "white",
        background: "linear-gradient(135deg, #365ACA, #4A90E2)",
        boxShadow: "4px 4px 12px rgba(54, 90, 202, 0.4)",
        textTransform: "uppercase",
        letterSpacing: 1.5,
        position: "relative",
        overflow: "hidden",
        "&::before": {
            content: '""',
            position: "absolute",
            width: "150%",
            height: "100%",
            top: 0,
            left: "-150%",
            background: "rgba(255,255,255,0.2)",
            transform: "skewX(-30deg)",
            transition: "left 0.8s ease-in-out",
        },
        "&:hover::before": { left: "150%" },
    },
    card_title: { color: "black", flexGrow: 1 },
    card: {
        py: 1,
        px: 2,
        boxShadow: "0px 8px 16px rgba(0, 0, 0, 0.15)",
        borderRadius: 3,
        flexGrow: 1,
        transition: "background 0.4s",
        border: "solid 1px rgba(0, 0, 0, 0.2)",
    },
    cardContent: { flexGrow: 1, display: "flex", flexDirection: "column", color: "black" },
    cardHeader: { display: "flex", justifyContent: "space-between", alignItems: "center" },
    pointsWrapper: { display: "flex", alignItems: "center" },
    progressBar: { height: 8, borderRadius: 5, bgcolor: "#e0e0e0", mt: 2 },
    progressText: { mt: 1, textAlign: "right" },
    buttonWrapper: { mt: 2, display: "flex", justifyContent: "space-between", alignItems: "center" },
    claimButton: {
        bgcolor: "#4CAF50",
        color: "white",
        width: "50%",
        borderRadius: 2,
        textTransform: "none",
        fontWeight: 600,
    },
};

export default styles;
